title: Juan Sebastian Frittaoni
description: Soy licenciado en Sociología y maestrando Explotación de Datos y Descubrimiento del Conocimiento. Data Scientist en el Ente de Turismo del Gobierno de la Ciudad de Buenos Aires. Interesado en Ciencia de Datos, Aprendizaje Automático y Ciencias Sociales. //  I'm a Sociologist interested in data science, machine learning and social sciences. I am currently working as a Data scientist at the Tourism Entity of the Buenos Aires City Goverment and pursuing a master's degree in Data Science.

theme: jekyll-theme-cayman
