title: Juan Sebastian Frittaoni
description: I'm a Sociologist interested in data science, machine learning and social sciences. I am currently pursuing a master's degree in Data science.

theme: jekyll-theme-cayman
