title: Juan Sebastian Frittaoni
description: Soy licenciado en sociología, interesado en Ciencia de Datos, Aprendizaje Automático y Ciencias Sociales. Acutlamente estoy cursando una Maestría en Explotación de Datos y Descubrimiento del Conocimiento. //  I'm a Sociologist interested in data science, machine learning and social sciences. I am currently pursuing a master's degree in Data Science.

theme: jekyll-theme-cayman
